### ISSUE TITLE
ERD 리뷰

### ISSUE THREAD

**Issue by parks38** [tabling-cloning/tabling-cloning-2022#1]
- ERD 에 대한 의문점/ 수정 반영 요청.
- 기능 명세를 작성하며 추가 필요한 테이블

**Comment by parks38** [comment]
Remote Reservation 테이블에서 오늘의 코드 불필요해 보임. 
=> 입력받은 코드와 오늘의 코드를 비교해 status check 만 해주면 될 것 같음.

**Comment by psymoney** [comment]
> Remote Reservation 테이블에서 오늘의 코드 불필요해 수정 필요 => 입력받은 코드와 오늘의 코드를 비교해 status check 만 해주면 될 것 같음.

오늘의 코드가 Store 테이블로 가면 될 것 같습니다.

**Comment by psymoney** [comment]
Reservation 테이블에 adult_cnt, kid_count 컬럼 추가 필요
실제 서비스에선 성인과 유아의 인원 수를 예약 시 입력하게 되어있음.
유아를 제외하고 실제 인원으로만 받게 되더라도 예약 시 인원 수 에 대한 정보가 테이블에 포함되어야 할 것으로 보임

**Comment by psymoney** [comment]
Remote Reservation 테이블에 adult_cnt, kid_cnt 컬럼 추가 필요
실제 서비스에선 성인과 유아의 인원 수를 예약 시 입력하게 되어있음.
유아를 제외하고 실제 인원으로만 받게 되더라도 대기열 신청 시 인원 수 에 대한 정보가 테이블에 포함되어야 할 것으로 보임

**Comment by psymoney** [comment]
#### Remote Reservation 테이블명 Queue 또는 Table Queue 등으로 변경
Remote Reservation 테이블은 원격 대기열 기능을 수행과 관련되어 있고, Reservation 테이블은 예약 기능과 관련되어 있으므로 각각의 명칭과 기능이 일치하는 테이블명을 갖는 것이 좋을 것 같습니다.
Queue는 자료구조 명칭과 중복되므로 Table Queue가 좋을 것 같습니다.

**Comment by jun111haha** [comment]
## USER 테이블에 회원 핸드폰번호 추가

**Comment by psymoney** [comment]
> ### USER 테이블에 회원 핸드폰번호 추가
> 실제 서비스에 대기열에 등록할시에
> 핸드폰번호를 추가하는 경우가 있었음 노쇼방지를 위해 핸드폰번호 컬럼추가 해야 좋을것같음.
> 이건 회원정보에 추가할지, 예약테이블에 추가해야할지 논의가필요

해당 내역 관련해서 현장 대기인원에 대한 유저 데이터를 어떻게 정의할지 논의도 필요할 것 같아요.

혼자 생각했을땐 Anonymous 계정 하나로 등록하는 상황을 고려했는데, 핸드폰번호 같은 고유 식별 정보로 노쇼 현황등을 기록해야 한다면 좀 더 논의가 필요할 것 같습니다.

현장 대기열 기능을 고려하지 않는 방법도 있겠지만... 화요일에 같이 얘기해보면 좋을 주제 같아요!

**Comment by parks38** [comment]
> ### USER 테이블에 회원 핸드폰번호 추가
> 실제 서비스에 대기열에 등록할시에 핸드폰번호를 추가하는 경우가 있었음 노쇼방지를 위해 핸드폰번호 컬럼추가 해야 좋을것같음. 이건 회원정보에 추가할지, 예약테이블에 추가해야할지 논의가필요

노쇼 위한 핸드폰 번호를 쓰게 되면 개인정보에 대한 부분에 우려가 있을것 같아서
그렇게 하기 보다는 USER 노쇼 카운팅을 해서 3번 이상 노쇼일 경우 얼마 기간동안 기능을 못쓰도록 설정해 두는 것이 좋을것 같다는 생각을 해보았습니다. 카카오톡으로만 회원가입이 가능하고 (대부분 사람들은 하나의 카카오톡 계정을 가지고 있다고 가정을 한다면) 노쇼현황에 대한 필드를 추가하여 식별할수 있다면 좋을 것 같아요. 현장 대기열도 똑같이 노쇼를 해당 방법으로 체크하고 같이 적용시키고요! 

노쇼에 대한 기능은 저도 자세하개 고려해보지 못한 부분이였는데 중요한 기능일 것 같습니다!
