### ISSUE TITLE
상세 기능 명세 documentation 

### ISSUE THREAD

**Issue by parks38** [tabling-cloning/tabling-cloning-2022#2]
- 페이지 당 상세 필요 기능 명세 
- 구현하고 싶은 추가 기능 상의
- 담당하고 싶은 기능

**Comment by psymoney** [comment]
### 원격/현장 대기열 통합 이슈
|                           | 원격 고객 | 현장 고객 | 업주 |
| ----------------- | ---------- | ----------- | ----- |
| 원격/현장 분리 | 각각의 대기열로 인해 불편요소 없을 것으로 예상 | 원격 고객과 동일 | 점주과 관리해야 하는 대기열이 두개가 되어 대기열 관리가 영업관리측면에서 편의성을 저하시킬 가능성 (ex. 두 대기열 중 먼저 온 손님을 각각 비교하는 경우) |
| 원격/현장 통합 | 현장에서 대기열 등록하는 불편함 없이 동일한 대기열 이용하므로 편의성 증대 | 알고리즘에 따라 현장 대기 시간이 길어질 수 있음 -> 부정적 경험 | 원격 고객의 노쇼/취소 또는 대기 확정율이 낮은 환경이라면 대기시간 알고리즘에 따라 신청 전 대기시간이 증가해 대기열 신청 자체를 안할 가능성 |

예상대기시간 산출 및 대기열 관리 알고리즘이 확정되지 않은 상황에서 개인적으로 고려해본 상황별, 이해관계자별 이슈입니다.
아니라고 생각되는 부분들 부담없이 서로 얘기 나눴으면 합니다~

그리고 현재 테이블링 서비스에서 원격대기는 업주가 원격 대기 허용 여부를 설정할 수 있게 해 둔 것으로 보입니다. 원격대기 자체가 비활성화 되어 있는 업체들이 몇몇있습니다. 아무래도 서비스 공급자가 정해둔 정책을 모든 업주에게 관철시키기 어려울 수 있을것 같아 이렇게 했을 것 같다는 생각이 드네요.

**Comment by psymoney** [comment]
### [기능] 노쇼/취소에 따른 원격 대기 신청 금지 기능
현재 테이블링 서비스에 존재하는 기능으로, 노쇼 또는 취소 시 페널티가 부과될 수 있다고 합니다.
서비스 관점에서는 블랙컨슈머 이슈를 해결할 수 있는 좋은 수단으로 보여 서비스 구현 시 추가한다면 좋을 것 같습니다.

**Comment by jun111haha** [comment]
[기능추가]

**Comment by psymoney** [comment]
> ### 원격/현장 대기열 통합 이슈
> 원격 고객	현장 고객	업주
> 원격/현장 분리	각각의 대기열로 인해 불편요소 없을 것으로 예상	원격 고객과 동일	점주과 관리해야 하는 대기열이 두개가 되어 대기열 관리가 영업관리측면에서 편의성을 저하시킬 가능성 (ex. 두 대기열 중 먼저 온 손님을 각각 비교하는 경우)
> 원격/현장 통합	현장에서 대기열 등록하는 불편함 없이 동일한 대기열 이용하므로 편의성 증대	알고리즘에 따라 현장 대기 시간이 길어질 수 있음 -> 부정적 경험	원격 고객의 노쇼/취소 또는 대기 확정율이 낮은 환경이라면 대기시간 알고리즘에 따라 신청 전 대기시간이 증가해 대기열 신청 자체를 안할 가능성
> 예상대기시간 산출 및 대기열 관리 알고리즘이 확정되지 않은 상황에서 개인적으로 고려해본 상황별, 이해관계자별 이슈입니다. 아니라고 생각되는 부분들 부담없이 서로 얘기 나눴으면 합니다~
> 
> 그리고 현재 테이블링 서비스에서 원격대기는 업주가 원격 대기 허용 여부를 설정할 수 있게 해 둔 것으로 보입니다. 원격대기 자체가 비활성화 되어 있는 업체들이 몇몇있습니다. 아무래도 서비스 공급자가 정해둔 정책을 모든 업주에게 관철시키기 어려울 수 있을것 같아 이렇게 했을 것 같다는 생각이 드네요.

예약과 원격 줄서기를 각각 현장줄서기 원격줄서기로 이해했었는데 예약하기는 일정과 시간입력해서 예약하는 것이었네요..
기본적으로 원격/현장 줄서기가 한 큐에 포함되는게 맞는 것 같습니다.

**Comment by psymoney** [comment]
### [기능추가] 예약하기 - KakaoPushService 기능
예약 시, 예약 당일에 카카오 메세지 알림 기능도 추가되면 좋을 것 같습니다.
아니면 카카오 캘린더로 일정 쏴주는 것도 노쇼 관리에 도움 될 듯 합니다.

**Comment by psymoney** [comment]
### [상세기능] 원격 줄서기 - 매장 영업시간에 따라 대기열 자동 활성/비활성화 기능
매장 운영시간이 아닐 경우, 원격 줄서기 기능이 비활성화 되고,
반대로 운영시간에는 원격 줄서기가 활성화 되는 기능

해당 기능을 적용하려면 work_day 테이블의 컬럼 및 데이터 타입에 수정이 필요할 것 같습니다.

**Comment by psymoney** [comment]
[상세기능] 원격 줄서기 - 기존 대기열에 반영되어 있는 고객은 타 매장 원격 대기열 이용 불가
(정책에 따라) 원격 줄서기로 특정 status를 충족하였다면, 타 매장 원격 대기열을 이용 불가능하게 하는 기능이 필요할 것 같습니다.
다중 대기열 등록을 하더라도 최종적으로 이용하는 매장은 하나이므로, 대기 예상 시간 및 대기열 혼선으로 다른 고객의 편의성을 저하할 수 있으므로 해당 기능이 필요할 것 같습니다.

**Comment by jun111haha** [comment]
### [상세기능]
원격줄서기 신청시에 한 매장에 줄서기 신청시 3번이상 신청취소하면 30분동안 신청못하는 패널티 부과하는 기능을 추가해야할것 같습니다.

**Comment by parks38** [comment]
> ### [상세기능] 원격 줄서기 - 매장 영업시간에 따라 대기열 자동 활성/비활성화 기능
> 매장 운영시간이 아닐 경우, 원격 줄서기 기능이 비활성화 되고, 반대로 운영시간에는 원격 줄서기가 활성화 되는 기능
> 
> 해당 기능을 적용하려면 work_day 테이블의 컬럼 및 데이터 타입에 수정이 필요할 것 같습니다.

아래 코멘트도 함께 취합해서 기능에 대해서 생각해 보면 좋을 것 같습니다. 

> 업주입장에서 대기가 몇팀이상일때 원격줄서기 불가하는 기능 추가

음식점 테이블에 원격줄서기와 예약받기 두개의 기능을 수동적으로 활성화/비활성화 되또록 관리할수 있게끔 하는것도 좋을것 같습니다. 
오픈시간에 업주는 준비가 안되어 있는데 원격줄서기나/ 예약하기가 가능하다면 곤란할것 같습니다. 

이 기능에 대한 부분은 조금 더 취합하여 화요일날 나눠볼게요 😄
