### ISSUE TITLE
유저 - black consumer 정책

### ISSUE THREAD

**Issue by parks38** [tabling-cloning/tabling-cloning-2022#5]
블랙 컨수머 정책을 위해 추가 고민 사항들 입니다. 
-  휴대폰 번호 -> 안심번호 API(사용 가능한지 확인)/회원 테이블
    - 안심번호 무료로 이용 가능한지 확인 필요. 
        -  안심 번호 자체 생성 
    - Hash해서 예약했을 시에만 보이도록 설정?
- no-show 방지 
    - 나중에 정책에 대한 알고리즘을 추가한다고 가정 했을 시, 해당 필드만 추가하면 괜찮을지 확인 필요 
- 줄서기 신청시 해당 3번 이상 같은 매장 신청 취소 하면 30분 이상 신청 못하는 패널티 부과
- 타 매장 3개까지 이용 가능 이상은 원격 줄서기 이용 불가

**Comment by jun111haha** [comment]
안심번호API 조사해보니까 무료는 없는것같구 소량의건도 유료로 책정되서 요금이 부과되네요 다른걸로 대체하거나 다른 방안 생각해봐야 할 것 같네요.
