### ISSUE TITLE
예약하기 - 활성화/비활성화

### ISSUE THREAD

**Issue by parks38** [tabling-cloning/tabling-cloning-2022#6]
예약하기/ 줄서기에 대해서 모두 활성화/비활성화 가능하도록 할 예정입니다. 
- store 에 기재한 운영시간에 맞춰 활성화/ 비활성화 (자동)
- owner 이 직접 비활성화/활성화 수동 기입 가능하도록 설정 (수동)

자동과 수동 모두 가능하게 하려면 어떤 테이블 혹은 필드가 추가적으로 필요 할까요?

**Comment by jun111haha** [comment]
운영시간 같은경우는 요일마다 운영시간이 달라질수 있으므로 영업일 테이블에 필드 추가하는게 나아보입니다! 직접 비활성화/활성화 같은경우는 매장테이블에 필드하나를 추가하여 관리하면 될것같은데 어떤가요!?

**Comment by parks38** [comment]
[매장]
| 필드 | 타입 | 
|---|---|
| id| BIGINT |
| 줄서기 활성화 | BIT |
| 예약 활성화 | BIT |

[영업시간]
|필드 | 타입|
|---|---|
| id | BIGINT |
| 날짜 | tinyint |
| 시작시간 | time|
|종료시간 | time|

- 줄서기 활성화는 영업 시간 내에 on/off
- 예약하기 기능은 시간 사용 필요 없음으로 turn on/off 만 가능하고 자동으로 활성화/비활성화 기능은 없을 예정입니다. 
    - DEFAULT : 활성화
