### ISSUE TITLE
UX Flow Chart 공유하기

### ISSUE THREAD

**Issue by parks38** [tabling-cloning/tabling-cloning-2022#7]
인당 4개의 UX 플로우를 제작하여 빠진 기능들을 추가하려고 합니다. 

프로그램 기능들에 대한 부분은 해당 링크에서 참고하시면 될것 같습니다
=> https://github.com/tabling-cloning/tabling-cloning-2022/wiki/%5B%233%5D-2022-05-03

UX 플로우에 대한 부분을 자유롭게 적어주시고 추가될 기능들도 함께 토론해 주세요.

**Comment by psymoney** [comment]
[UX flow](https://www.figma.com/file/JqvPq5XGrHOOouyajC8dNg/Tabling?node-id=0%3A1)
작성 중인 내역 링크입니다.

그리다보니 예약/줄서기/리뷰 확인을 위한 유저 마이페이지 필요해보입니다.

**Comment by parks38** [comment]
![image](https://user-images.githubusercontent.com/16564373/167540706-7d1c9333-51d4-4236-8656-aa0cb2329d2b.png)

[추가 페이지]
* 마이페이지 
  - 고객용
      - 나의 예약 현황
      - 나의 정보
      - 줄서기 현황
  - 오너용
     - 나의 정보
     - 줄서기 현황
     - 예약 현황 

* 개인 notification page (push alarm)
  -> 추가에 대한 내용 필요

**Comment by psymoney** [comment]
[백엔드 push notification 구현 참고자료](https://tech.junhabaek.net/%EB%B0%B1%EC%97%94%EB%93%9C-%EC%84%9C%EB%B2%84-%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98-presentation-layer-3-%EC%9D%91%EB%8B%B5-%EC%9C%A0%ED%98%95%EC%97%90-%EB%94%B0%EB%A5%B8-variation-2-push-notification-1eacb4df4a7e)

@parks38 혹시 UX flow list 구글 document나 노션으로 공유해주실 수 있을까요?

**Comment by jun111haha** [comment]
![스토어](https://user-images.githubusercontent.com/59434443/167614251-1e3020b0-d762-4047-a001-9ad6ce0f1543.jpg)

**Comment by jun111haha** [comment]
![오너 줄서기](https://user-images.githubusercontent.com/59434443/167614351-f9bb8fa7-4b0c-47ea-91e7-255dc4679590.jpg)

**Comment by jun111haha** [comment]
![에약](https://user-images.githubusercontent.com/59434443/167614423-c96f6e2b-0d60-4f55-a4d2-da1f785a4d39.jpg)

**Comment by jun111haha** [comment]
점주가 스토어 등록했을때 심사처리 방안
